---
- hosts: plusberry
  vars:
    ansible_db_pass: 'Open1234'
  tasks:
  - name: install ansible and pip
    become: yes
    become_user: root
    apt: name {{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - ansible
    - python-pip
    - git

  - name: config ansible
    become: yes
    become_user: root
    template:
      src: "client.ansible.cfg.j2"
      dest: "/etc/ansible/ansible/cfg"
      owner: root
      group: root
      mode: 0600
  
  - name: download dynamic inventory scripts
    become: yes
    become: root
    git: repo=git@github.com:acaracappa/ansible-dynamic-inventory-mysql.git
         dest=/root/ 
         accept_hostkey=yes
         force=yes
         recursive=no
         key_file=/Users/gibor/Projects/plusberry/pi_github_rsa
  
  - name: create database
    become: yes
    become_user: root
    mysql_db: name=inventory state=present collation=utf8_general_ci
 
  - name: create db tables
    become: yes
    become_user: root
    mysql_db: name=inventory tate=import target=/root/ansible-dynamic-inventory-mysql/tables.sql

  - name: create database user
    become: yes 
    become_user: root
    mysql_user: 
      name: anaible 
      password: "{{ ansible_db_pass  }}"
      priv: '*.*:ALL' 
      state: present

  - name: rename modified mysql.ini
    become: yes
    become_user: root
    command: cp /root/ansible-dynamic-inventory-mysql/mysql.ini.dist /root/ansible-dynamic-inventory-mysql/mysql.ini
  - name: set mysql.ini host
    become: yes
    become_user: root
    lineinfile:
      dest: /root/ansible-dynamic-inventory-mysql/mysql.ini
      regexp: "host = YOURHOST"
      line: "host = localhost"
  - name: set mysql.ini user
    become: yes
    become_user: root
    lineinfile:
      dest: /root/ansible-dynamic-inventory-mysql/mysql.ini
      regexp: "user = YOURUSER"
      line: "user = ansible"
  - name: set mysql.ini password
    become: yes
    become_user: root
    lineinfile:
      dest: /root/ansible-dynamic-inventory-mysql/mysql.ini
      regexp: "passwd = YOURPASSWORD"
      line: "passwd = {{ ansible_db_pass }}"
  - name: set mysql.ini datanasme name  
    become: yes
    become_user: root
    lineinfile:
      dest: /root/ansible-dynamic-inventory-mysql/mysql.ini
      regexp: "db = YOURDB"
      line: "db = inventory"
