---
- hosts: plusberry
  vars:
    new_disk: '/dev/sda'
    vg_name: 'vg_plusberry'
    lv_name: 'lv_plusberry'
    lv_size: '100%FREE' 
    filesystem: 'ext4'
    new_mntp: '/home/pi/ssd'
  tasks:
    - name: install lvm2
      become: yes
      apt: name=lvm2 state=present
 
    - name: creating new LVM volume group
      become: yes
      lvg: vg={{ vg_name }} pvs={{ new_disk }} state=present

    - name: creating new LVM logical volume
      become: yes
      lvol: vg={{ vg_name }} lv={{ lv_name }} size={{ lv_size }} state=present
    
    - name: creating new filesystem on new LVM logical volume
      become: yes
      filesystem: fstype={{ filesystem }} dev=/dev/{{ vg_name }}/{{ lv_name }}
 
    - name: mounting new filesystem
      become: yes
      mount: name={{ new_mntp }} src=/dev/{{ vg_name }}/{{ lv_name }} fstype={{ filesystem }} state=mounted

