---
- hosts: plusberry
# gather_facts: no
  vars:
    mysql_root_pw: open
  tasks:
  - name: install mysql 
    become: yes
    become_user: root
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  - name: start mysql service
    become: yes
    become_user: root
    service:
      name: mysql
      state: started
      enabled: true
  - name: update mysql root pw
    become: yes
    become_user: root
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_pw }}"
      login_user: root
      login_password: "{{ mysql_root_pw }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
      state: present
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  - name: Create .my.cnf
    become: yes
    become_user: root
    template:
      src: "client.my.cnf.j2"
      dest: "/root/.my.cnf"
      owner: root
      group: root
      mode: 0600
