---
- hosts: plusberry
  gather_facts: no
  tasks: 
  - name: install diagnostic utilities
    become: yes
    become_user: root
    apt: name {{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - htop
    - iftop
    - mytop
