---
- hosts: plusberry
  gather_facts: no
  tasks: 
  - name: install diagnostic utilities
    become: yes
    become_user: root
    apt: name {{ item }} state=present
    with_items:
    - htop
    - iftop
    - mytop
    - locate
