---
- hosts: plusberry
  gather_facts: no
  tasks: 
  - name: install diagnostic utilities
    become: yes
    apt: name={{ item }} state=installed update_cache=true cache_valid_time=3600
    with_items:
    - vim
    - htop
    - iftop
    - mytop
    - locate
    - syslog-ng
